# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_stages_email', '0004_emailstage_activate_user_on_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailstage',
            options={'verbose_name': '电子邮件阶段', 'verbose_name_plural': '电子邮件阶段'},
        ),
        migrations.AlterField(
            model_name='emailstage',
            name='activate_user_on_success',
            field=models.BooleanField(default=False, help_text='完成阶段后激活用户。'),
        ),
        migrations.AlterField(
            model_name='emailstage',
            name='token_expiry',
            field=models.IntegerField(default=30, help_text='发出令牌的有效时间（单位为分钟）。'),
        ),
        migrations.AlterField(
            model_name='emailstage',
            name='use_global_settings',
            field=models.BooleanField(default=False, help_text='启用后，将使用全局电子邮件连接设置，下面的连接设置将被忽略。'),
        ),
    ]
