# 来源标识
SOURCE: pwf

# 导出的数据库配置
MYSQL_HOST: huofu.vip
MYSQL_PORT: 33044
MYSQL_DATABASE: wallet
MYSQL_USERNAME: root
MYSQL_PASSWORD: 5a47919bab377c4e

# 导入的数据库配置
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: authentik
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: 123123
