# 来源标识
SOURCE: pwf

# 导出的数据库配置
MYSQL_HOST: 
MYSQL_PORT: 
MYSQL_DATABASE: 
MYSQL_USERNAME: 
MYSQL_PASSWORD: 

# 导入的数据库配置
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: authentik
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: 123123
