# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_policies_expiry', '0002_passwordexpirypolicy_authentik_p_policy__cf73a7_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordexpirypolicy',
            options={'verbose_name': '密码过期策略', 'verbose_name_plural': '密码过期策略'},
        ),
    ]
