# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_providers_proxy', '0015_proxyprovider_receive_header_auth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyprovider',
            options={'verbose_name': '代理提供程序', 'verbose_name_plural': '代理提供程序'},
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='basic_auth_enabled',
            field=models.BooleanField(default=False, help_text='根据来自 authentik 的值设置自定义 HTTP-Basic 身份验证标头。', verbose_name='设置 HTTP-Basic 身份验证'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='basic_auth_password_attribute',
            field=models.TextField(blank=True, help_text='用于 HTTP-Basic 标头的密码部分的用户/组属性。', verbose_name='HTTP-Basic 密码密钥'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='basic_auth_user_attribute',
            field=models.TextField(blank=True, help_text='用于 HTTP-Basic 标头用户名部分的用户/组属性。如果未设置，则使用用户的电子邮件地址。', verbose_name='HTTP-Basic 用户名密钥'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='intercept_header_auth',
            field=models.BooleanField(default=True, help_text='启用时，此提供程序将会拦截 Authorization 标头，并基于其值认证请求。'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='internal_host_ssl_validation',
            field=models.BooleanField(default=True, help_text='验证上游服务器的 SSL 证书', verbose_name='内部主机 SSL 验证'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='mode',
            field=models.TextField(choices=[('proxy', 'Proxy'), ('forward_single', 'Forward Single'), ('forward_domain', 'Forward Domain')], default='proxy', help_text='在 traefik 和 nginx auth_request 中启用对 ForwardAuth 的支持。排除 internal_host。'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='skip_path_regex',
            field=models.TextField(blank=True, default='', help_text='用于描述何处不需要身份验证的正则表达式。每个新行都被解释为一个新的正则表达式。'),
        ),
    ]
