# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_policies_event_matcher', '0023_alter_eventmatcherpolicy_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmatcherpolicy',
            options={'verbose_name': '事件匹配策略', 'verbose_name_plural': '事件匹配策略'},
        ),
        migrations.AlterField(
            model_name='eventmatcherpolicy',
            name='action',
            field=models.TextField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('user_write', 'User Write'), ('suspicious_request', 'Suspicious Request'), ('password_set', 'Password Set'), ('secret_view', 'Secret View'), ('secret_rotate', 'Secret Rotate'), ('invitation_used', 'Invite Used'), ('authorize_application', 'Authorize Application'), ('source_linked', 'Source Linked'), ('impersonation_started', 'Impersonation Started'), ('impersonation_ended', 'Impersonation Ended'), ('flow_execution', 'Flow Execution'), ('policy_execution', 'Policy Execution'), ('policy_exception', 'Policy Exception'), ('property_mapping_exception', 'Property Mapping Exception'), ('system_task_execution', 'System Task Execution'), ('system_task_exception', 'System Task Exception'), ('system_exception', 'System Exception'), ('configuration_error', 'Configuration Error'), ('model_created', 'Model Created'), ('model_updated', 'Model Updated'), ('model_deleted', 'Model Deleted'), ('email_sent', 'Email Sent'), ('update_available', 'Update Available'), ('custom_', 'Custom Prefix')], default=None, help_text='将创建的事件与此操作类型匹配。留空时，所有操作类型都将匹配。', null=True),
        ),
        migrations.AlterField(
            model_name='eventmatcherpolicy',
            name='app',
            field=models.TextField(default=None, help_text='匹配选定应用程序创建的事件。如果留空，则匹配所有应用程序。', null=True),
        ),
        migrations.AlterField(
            model_name='eventmatcherpolicy',
            name='client_ip',
            field=models.TextField(default=None, help_text='匹配事件的客户端 IP（严格匹配，要匹配网段请使用表达式策略）', null=True),
        ),
    ]
