# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_stages_dummy', '0002_dummystage_throw_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummystage',
            options={'verbose_name': '虚拟阶段', 'verbose_name_plural': '虚拟阶段'},
        ),
    ]
