# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_policies_password', '0005_passwordpolicy_check_have_i_been_pwned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordpolicy',
            options={'verbose_name': '密码策略', 'verbose_name_plural': '密码策略'},
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='hibp_allowed_count',
            field=models.PositiveIntegerField(default=0, help_text='密码哈希允许出现在 HaveIBeenPwned 中多少次'),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='password_field',
            field=models.TextField(default='password', help_text='要检查的字段键，可以使用输入阶段中定义的字段键。'),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='zxcvbn_score_threshold',
            field=models.PositiveIntegerField(default=2, help_text='如果 zxcvbn 分数小于等于此值，则策略失败。'),
        ),
    ]
