# Generated by Django 3.2.6 on 2024-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_policies_reputation', '0005_reputation_expires_reputation_expiring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reputationpolicy',
            options={'verbose_name': '信誉策略', 'verbose_name_plural': '信誉策略'},
        ),
    ]
