# Generated by Django 4.2.6 on 2024-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_core", "0032_group_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verify_email",
            field=models.BooleanField(default=True),
        ),
    ]
