# Generated by Django 3.2.6 on 2024-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_core', '0033_user_is_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_send_email',
            field=models.BooleanField(default=True),
        ),
    ]
